### ISSUE TITLE
Frontend - Formular 

### ISSUE THREAD

**Issue by Katharina-Groller** [mrbubbles-src/dci-final-project-roomtwenty-booknook#27]
Ein Formular für nicht vorhandene Bücher zum Hinzufügen in der DB.
User gibt an:
        - Cover
	- Titel
	- Autor
	- Beschreibung
	- Seitenanzahl
	- Verlag
	- (Neu)Preis

User sendet das formular hab Admin oder mod bekommt nachricht, Buch wird gepürft und Freigegeben.

**Comment by Mysterio-WebMaster** [comment]
Hi, I am interested to know more... can you make it in english so that it will be easy for me to read and collaborate.
